version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  local-producer:
    build: local-producer/.

# TODO add vault
#  vault:
#    build: vault/.
#    image: vault
#    ports:
#      - 8200:8200
#    environment:
#      VAULT_TOKEN: secret-root-token
#      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
#      VAULT_ADDR: http://0.0.0.0:8200/
#      VAULT_APP_ROLE: app-notifications-consumer
#      VAULT_ROLE_ID: insert-prefix-notifications-consumer
#      VAULT_SECRET_ID: insert-prefix-notifications-consumer
#    command: /opt/setup-and-run-vault.sh
